# Netlify configuration file

[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and rewrites for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200